### ISSUE TITLE
is it possible to add locale support to widgets by set the default label attribute of fields to its translation?

### ISSUE THREAD

**Issue by pymalch** [TurboGears/tgext.admin#4]
for example in: 
admin/widgets.py in _BootstrapAdminFormMixin for forms 
and 
admin/widgets.py in BoostrapAdminTableBase for table headers

although i override these for my usage but i thought its better to suggest.
    class _LocalizedBootstrapAdminFormMixin(_BootstrapAdminFormMixin):
        def _admin_init_attrs(self):
            for f in self.__fields__:
                if not hasattr(self.__field_widget_args__[f], 'label'):
                    self.__field_widget_args__[f]['label']= l_(f)

**Comment by amol-** [comment]
This is actually not related to tgext.admin itself, it is probably something that should be changed in sprox to provide i18n in name2label https://github.com/TurboGears/sprox/blob/master/sprox/util.py#L85

Should be possible to achieve this using tw2.core.i18n._ and let the framework provide the right gettext function.

**Comment by pymalch** [comment]
is it possible to be done?
